from MIDI import NoteOn, NoteOff, CC

mappings = {
    "volume": CC(0),
    "pan": CC(1),
    "send_a": CC(2),
    "send_b": CC(3),
    "send_c": CC(4),
    "send_d": CC(5),

    "macro_1": CC(6),
    "macro_2": CC(7),
    "macro_5": CC(8),
    "macro_6": CC(9),
    "scroll_tracks": CC(10),
    "scroll_scenes": CC(11),

    "macro_3": CC(12),
    "macro_4": CC(13),
    "macro_7": CC(14),
    "macro_8": CC(15),
    "scrub_by": CC(16),
    "midi_recording_quantization": CC(17),

    "stop": NoteOn(0),
    "play": NoteOn(1),
    "pause": NoteOff(1),
    "overdub_on": NoteOn(2),
    "overdub_off": NoteOff(2),
    "metronome_on": NoteOn(3),
    "metronome_off": NoteOff(3),
    "undo": NoteOn(4),
    "redo": NoteOn(5),
    "session_automation_rec_on": NoteOn(6),
    "session_automation_rec_off": NoteOff(6),
    "arm": NoteOn(7),
    "unarm": NoteOff(7),
    "create_clip": NoteOn(8),
    "double_clip": NoteOn(9),
    "delete_clip": NoteOn(10),
    "solo": NoteOn(11),
    "unsolo": NoteOff(11),
    "prev_track": NoteOn(12),
    "next_track": NoteOn(13),
    "duplicate_clip": NoteOn(14),
    "mute": NoteOn(15),
    "unmute": NoteOff(15),
    "fire_next_scene": NoteOn(16)
}
